import SwiftUI

// MARK: - 终端行类型
enum TerminalLineKind {
    case userMessage    // 用户提问
    case toolCall       // 工具调用（Read/Write/Bash/Search）
    case toolResult     // 工具结果
    case thinking       // AI思考中
    case code           // 代码行
    case status         // 状态信息
    case spacer         // 空行
    case separator      // 分隔线
}

// MARK: - 终端行
struct TerminalLine: Identifiable {
    let id = UUID()
    let text: String
    let color: Color
    let kind: TerminalLineKind
    
    init(text: String, color: Color = .white, kind: TerminalLineKind = .code) {
        self.text = text
        self.color = color
        self.kind = kind
    }
}

// MARK: - AI代码生成器（opencode 风格）
class AICodeGenerator {
    
    // 模拟的用户提问 + AI 响应序列
    private let conversations: [[TerminalLine]] = [
        // 对话1：重构组件
        [
            .init(text: "  I'll help you refactor the authentication module. Let me first", color: .white, kind: .code),
            .init(text: "  examine the current implementation.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] src/auth/AuthProvider.tsx", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 245 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] src/auth/useAuth.ts", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 89 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] src/auth/types.ts", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 34 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  I see several issues with the current auth implementation.", color: .white, kind: .code),
            .init(text: "  The token refresh logic is duplicated and error handling is", color: .white, kind: .code),
            .init(text: "  inconsistent. Let me refactor it into a cleaner architecture.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Write] src/auth/AuthProvider.tsx", color: .yellow, kind: .toolCall),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    import { createContext, useCallback, useReducer } from 'react';", color: Color(red: 0.8, green: 0.5, blue: 1.0), kind: .code),
            .init(text: "    import { AuthService } from './service';", color: Color(red: 0.8, green: 0.5, blue: 1.0), kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    interface AuthState {", color: .blue, kind: .code),
            .init(text: "      user: User | null;", color: .white, kind: .code),
            .init(text: "      token: string | null;", color: .white, kind: .code),
            .init(text: "      isLoading: boolean;", color: .white, kind: .code),
            .init(text: "      error: string | null;", color: .white, kind: .code),
            .init(text: "    }", color: .blue, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    type AuthAction =", color: .blue, kind: .code),
            .init(text: "      | { type: 'LOGIN_START' }", color: .white, kind: .code),
            .init(text: "      | { type: 'LOGIN_SUCCESS'; payload: { user: User; token: string } }", color: .white, kind: .code),
            .init(text: "      | { type: 'LOGIN_FAILURE'; payload: string }", color: .white, kind: .code),
            .init(text: "      | { type: 'LOGOUT' };", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Written 156 lines to src/auth/AuthProvider.tsx", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Write] src/auth/useAuth.ts", color: .yellow, kind: .toolCall),
            .init(text: "  ✓ Written 42 lines to src/auth/useAuth.ts", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Refactoring complete! 3 files modified, 0 errors", color: .green, kind: .status),
        ],
        
        // 对话2：修复 Bug
        [
            .init(text: "  Let me investigate the WebSocket handler for memory leaks.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Search] WebSocket handler across codebase", color: .pink, kind: .toolCall),
            .init(text: "  Found 12 references in 4 files", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] src/services/websocket.ts", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 178 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  Found the issue! The event listeners in the connect() method", color: .white, kind: .code),
            .init(text: "  are never cleaned up on disconnect. Each reconnection adds", color: .white, kind: .code),
            .init(text: "  duplicate listeners that hold references to the old socket.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Edit] src/services/websocket.ts", color: .yellow, kind: .toolCall),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    - this.socket.addEventListener('message', handler);", color: .red, kind: .code),
            .init(text: "    - this.socket.addEventListener('close', onClose);", color: .red, kind: .code),
            .init(text: "    + const controller = new AbortController();", color: .green, kind: .code),
            .init(text: "    + const signal = controller.signal;", color: .green, kind: .code),
            .init(text: "    + this.socket.addEventListener('message', handler, { signal });", color: .green, kind: .code),
            .init(text: "    + this.socket.addEventListener('close', onClose, { signal });", color: .green, kind: .code),
            .init(text: "    + this.abortControllers.push(controller);", color: .green, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Applied 2 changes to src/services/websocket.ts", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Bash] npm test -- --filter websocket", color: Color(red: 1.0, green: 0.6, blue: 0.4), kind: .toolCall),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    PASS  src/__tests__/websocket.test.ts", color: .green, kind: .code),
            .init(text: "      ✓ connects to server", color: .green, kind: .code),
            .init(text: "      ✓ handles reconnection", color: .green, kind: .code),
            .init(text: "      ✓ cleans up listeners on disconnect", color: .green, kind: .code),
            .init(text: "      ✓ no memory leak after 100 reconnections", color: .green, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    Tests: 4 passed, 4 passed", color: .green, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Memory leak fixed! All tests passing", color: .green, kind: .status),
        ],
        
        // 对话3：添加 API 路由
        [
            .init(text: "  I'll add full CRUD endpoints for products. Let me check the", color: .white, kind: .code),
            .init(text: "  existing API structure first.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Grep] route patterns in src/api/", color: .pink, kind: .toolCall),
            .init(text: "  Found: users.routes.ts, orders.routes.ts", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] src/api/users.routes.ts", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 67 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] src/models/Product.ts", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 28 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  I'll follow the existing pattern from users.routes.ts.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Write] src/api/products.routes.ts", color: .yellow, kind: .toolCall),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    import { Router } from 'express';", color: Color(red: 0.8, green: 0.5, blue: 1.0), kind: .code),
            .init(text: "    import { z } from 'zod';", color: Color(red: 0.8, green: 0.5, blue: 1.0), kind: .code),
            .init(text: "    import { auth } from '../middleware/auth';", color: Color(red: 0.8, green: 0.5, blue: 1.0), kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    const router = Router();", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    // GET /api/products", color: .gray, kind: .code),
            .init(text: "    router.get('/', auth, async (req, res) => {", color: .green, kind: .code),
            .init(text: "      const products = await Product.find()", color: .white, kind: .code),
            .init(text: "        .sort({ createdAt: -1 })", color: .white, kind: .code),
            .init(text: "        .limit(Number(req.query.limit) || 50);", color: .white, kind: .code),
            .init(text: "      res.json(products);", color: .white, kind: .code),
            .init(text: "    });", color: .green, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Written 124 lines to src/api/products.routes.ts", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Edit] src/api/index.ts", color: .yellow, kind: .toolCall),
            .init(text: "  ✓ Added products route registration", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ CRUD API complete! GET/POST/PUT/DELETE /api/products", color: .green, kind: .status),
        ],
        
        // 对话4：性能优化
        [
            .init(text: "  Let me profile the dashboard to find the bottlenecks.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] src/pages/Dashboard.tsx", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 312 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] src/hooks/useDashboardData.ts", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 156 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  I found 3 performance issues:", color: .white, kind: .code),
            .init(text: "  1. N+1 queries in useDashboardData — 8 sequential fetches", color: .yellow, kind: .code),
            .init(text: "  2. Missing React.memo on expensive chart components", color: .yellow, kind: .code),
            .init(text: "  3. No pagination on the activity log table", color: .yellow, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Edit] src/hooks/useDashboardData.ts", color: .yellow, kind: .toolCall),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    - const users = await fetchUsers();", color: .red, kind: .code),
            .init(text: "    - const orders = await fetchOrders();", color: .red, kind: .code),
            .init(text: "    - const metrics = await fetchMetrics();", color: .red, kind: .code),
            .init(text: "    + const [users, orders, metrics] = await Promise.all([", color: .green, kind: .code),
            .init(text: "    +   fetchUsers(),", color: .green, kind: .code),
            .init(text: "    +   fetchOrders(),", color: .green, kind: .code),
            .init(text: "    +   fetchMetrics(),", color: .green, kind: .code),
            .init(text: "    + ]);", color: .green, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Parallelized 3 API calls (8 sequential → 3 parallel)", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Edit] src/components/Charts.tsx", color: .yellow, kind: .toolCall),
            .init(text: "  ✓ Added React.memo to 4 chart components", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Edit] src/components/ActivityLog.tsx", color: .yellow, kind: .toolCall),
            .init(text: "  ✓ Added virtualized list with 50 items per page", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Dashboard optimized! Load time: 4.2s → 0.8s", color: .green, kind: .status),
        ],
        
        // 对话5：Git 操作
        [
            .init(text: "  Let me check what changes have been made.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Bash] git diff --stat", color: Color(red: 1.0, green: 0.6, blue: 0.4), kind: .toolCall),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    src/auth/AuthProvider.tsx     | 156 ++++++------", color: .white, kind: .code),
            .init(text: "    src/auth/useAuth.ts           |  42 +---", color: .white, kind: .code),
            .init(text: "    src/services/websocket.ts     |  23 ++-", color: .white, kind: .code),
            .init(text: "    src/pages/Dashboard.tsx       |  18 +-", color: .white, kind: .code),
            .init(text: "    4 files changed, 134 insertions(+), 105 deletions(-)", color: .gray, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Bash] git add -A && git commit -m \"refactor: improve auth, fix ws leak, optimize dashboard\"", color: Color(red: 1.0, green: 0.6, blue: 0.4), kind: .toolCall),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    [main f4a2c8d] refactor: improve auth, fix ws leak, optimize dashboard", color: .white, kind: .code),
            .init(text: "    4 files changed, 134 insertions(+), 105 deletions(-)", color: .gray, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Committed successfully!", color: .green, kind: .status),
        ],
        
        // 对话6：部署到生产环境
        [
            .init(text: "  I'll prepare and deploy the changes. Let me verify the", color: .white, kind: .code),
            .init(text: "  deployment configuration first.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] Dockerfile", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 34 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] .github/workflows/deploy.yml", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 89 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Bash] npm run build", color: Color(red: 1.0, green: 0.6, blue: 0.4), kind: .toolCall),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    > awesome-app@2.1.0 build", color: .gray, kind: .code),
            .init(text: "    > next build", color: .gray, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    ✓ Linting...", color: .green, kind: .code),
            .init(text: "    ✓ Compiled successfully", color: .green, kind: .code),
            .init(text: "    ✓ Generating static pages (42/42)", color: .green, kind: .code),
            .init(text: "    ✓ Build completed in 23.4s", color: .green, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Bash] docker build -t awesome-app:v2.1.0 .", color: Color(red: 1.0, green: 0.6, blue: 0.4), kind: .toolCall),
            .init(text: "  ✓ Successfully built image (245MB)", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Bash] kubectl apply -f k8s/deployment.yaml", color: Color(red: 1.0, green: 0.6, blue: 0.4), kind: .toolCall),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    deployment.apps/awesome-app configured", color: .white, kind: .code),
            .init(text: "    service/awesome-app unchanged", color: .white, kind: .code),
            .init(text: "    ingress/awesome-app configured", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Bash] kubectl rollout status deployment/awesome-app", color: Color(red: 1.0, green: 0.6, blue: 0.4), kind: .toolCall),
            .init(text: "    Waiting for rollout... 3/3 pods ready", color: .gray, kind: .code),
            .init(text: "    ✓ deployment successfully rolled out", color: .green, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Deployed v2.1.0 to production! 3 pods running", color: .green, kind: .status),
        ],
        
        // 对话7：添加单元测试
        [
            .init(text: "  Let me examine the payment service implementation first.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] src/services/PaymentService.ts", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 203 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] src/services/StripeAdapter.ts", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 145 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Grep] existing test files for payment", color: .pink, kind: .toolCall),
            .init(text: "  No test files found", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  I'll create comprehensive tests covering happy paths,", color: .white, kind: .code),
            .init(text: "  error handling, and edge cases.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Write] src/__tests__/PaymentService.test.ts", color: .yellow, kind: .toolCall),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    import { PaymentService } from '../services/PaymentService';", color: Color(red: 0.8, green: 0.5, blue: 1.0), kind: .code),
            .init(text: "    import { StripeAdapter } from '../services/StripeAdapter';", color: Color(red: 0.8, green: 0.5, blue: 1.0), kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    describe('PaymentService', () => {", color: .blue, kind: .code),
            .init(text: "      it('should process valid payment', async () => {", color: .white, kind: .code),
            .init(text: "        const result = await service.charge({", color: .white, kind: .code),
            .init(text: "          amount: 9999, currency: 'usd',", color: .white, kind: .code),
            .init(text: "          customerId: 'cus_123'", color: .white, kind: .code),
            .init(text: "        });", color: .white, kind: .code),
            .init(text: "        expect(result.status).toBe('succeeded');", color: .green, kind: .code),
            .init(text: "      });", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Written 287 lines to PaymentService.test.ts", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Bash] npm test -- --coverage", color: Color(red: 1.0, green: 0.6, blue: 0.4), kind: .toolCall),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    PASS  src/__tests__/PaymentService.test.ts", color: .green, kind: .code),
            .init(text: "      ✓ processes valid payment", color: .green, kind: .code),
            .init(text: "      ✓ handles insufficient funds", color: .green, kind: .code),
            .init(text: "      ✓ retries on network failure", color: .green, kind: .code),
            .init(text: "      ✓ validates card expiry date", color: .green, kind: .code),
            .init(text: "      ✓ applies discount codes correctly", color: .green, kind: .code),
            .init(text: "      ✓ handles currency conversion", color: .green, kind: .code),
            .init(text: "      ✓ emits payment webhook event", color: .green, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    Tests: 7 passed | Coverage: 94.2%", color: .green, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ 7 tests written, all passing with 94% coverage", color: .green, kind: .status),
        ],
        
        // 对话8：数据库 Schema 设计
        [
            .init(text: "  Let me check the existing database schema and patterns.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] prisma/schema.prisma", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 167 lines", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Glob] prisma/migrations/**/*.sql", color: .pink, kind: .toolCall),
            .init(text: "  Found 12 migration files", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  I'll design the notification schema following your", color: .white, kind: .code),
            .init(text: "  existing patterns with support for multiple channels.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Edit] prisma/schema.prisma", color: .yellow, kind: .toolCall),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "    model Notification {", color: .blue, kind: .code),
            .init(text: "      id          String   @id @default(cuid())", color: .white, kind: .code),
            .init(text: "      userId      String", color: .white, kind: .code),
            .init(text: "      type        NotificationType", color: .white, kind: .code),
            .init(text: "      channel     Channel  @default(IN_APP)", color: .white, kind: .code),
            .init(text: "      title       String", color: .white, kind: .code),
            .init(text: "      body        String", color: .white, kind: .code),
            .init(text: "      readAt      DateTime?", color: .white, kind: .code),
            .init(text: "      metadata    Json?", color: .white, kind: .code),
            .init(text: "      createdAt   DateTime @default(now())", color: .white, kind: .code),
            .init(text: "      user        User     @relation(fields: [userId])", color: .white, kind: .code),
            .init(text: "      @@index([userId, createdAt])", color: .gray, kind: .code),
            .init(text: "    }", color: .blue, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Added Notification model to schema", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Bash] npx prisma migrate dev --name add_notifications", color: Color(red: 1.0, green: 0.6, blue: 0.4), kind: .toolCall),
            .init(text: "  ✓ Migration applied successfully", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Write] src/services/NotificationService.ts", color: .yellow, kind: .toolCall),
            .init(text: "  ✓ Written 98 lines", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Notification system ready! Schema + Service created", color: .green, kind: .status),
        ],
        
        // 对话9：国际化
        [
            .init(text: "  Let me check the current i18n setup and extract strings.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Glob] src/locales/**/*.json", color: .pink, kind: .toolCall),
            .init(text: "  Found: en.json, zh.json", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] src/locales/en.json", color: .cyan, kind: .toolCall),
            .init(text: "  Reading file... 156 keys", color: .gray, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  I'll create Japanese and Korean locale files and update", color: .white, kind: .code),
            .init(text: "  the i18n configuration.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Write] src/locales/ja.json", color: .yellow, kind: .toolCall),
            .init(text: "  ✓ Written 156 translated keys", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Write] src/locales/ko.json", color: .yellow, kind: .toolCall),
            .init(text: "  ✓ Written 156 translated keys", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Edit] src/i18n/config.ts", color: .yellow, kind: .toolCall),
            .init(text: "  ✓ Added ja and ko to supported locales", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ i18n ready! 4 locales: en, zh, ja, ko", color: .green, kind: .status),
        ],
        
        // 对话10：安全审计
        [
            .init(text: "  I'll scan the codebase for common security vulnerabilities.", color: .white, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Bash] npm audit", color: Color(red: 1.0, green: 0.6, blue: 0.4), kind: .toolCall),
            .init(text: "  Found 3 moderate vulnerabilities", color: .yellow, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Grep] hardcoded secrets and API keys", color: .pink, kind: .toolCall),
            .init(text: "  Found 2 potential issues", color: .red, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Read] src/config/database.ts", color: .cyan, kind: .toolCall),
            .init(text: "  Found hardcoded connection string on line 12", color: .red, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  Issues found:", color: .yellow, kind: .code),
            .init(text: "  1. Hardcoded DB connection string in database.ts", color: .red, kind: .code),
            .init(text: "  2. Missing CSRF protection on /api/webhooks", color: .red, kind: .code),
            .init(text: "  3. SQL injection risk in search endpoint", color: .red, kind: .code),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Edit] src/config/database.ts", color: .yellow, kind: .toolCall),
            .init(text: "    - const url = \"postgres://admin:pass@host/db\";", color: .red, kind: .code),
            .init(text: "    + const url = process.env.DATABASE_URL;", color: .green, kind: .code),
            .init(text: "  ✓ Moved to environment variable", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Edit] src/api/webhooks.ts", color: .yellow, kind: .toolCall),
            .init(text: "  ✓ Added CSRF middleware", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  [Edit] src/api/search.ts", color: .yellow, kind: .toolCall),
            .init(text: "    - const q = `SELECT * FROM items WHERE name LIKE '%${term}%'`;", color: .red, kind: .code),
            .init(text: "    + const q = `SELECT * FROM items WHERE name LIKE $1`;", color: .green, kind: .code),
            .init(text: "  ✓ Parameterized query to prevent SQL injection", color: .green, kind: .toolResult),
            .init(text: "", color: .white, kind: .spacer),
            .init(text: "  ✓ Security audit complete! 3 vulnerabilities fixed", color: .green, kind: .status),
        ],
    ]
    
    // 模拟的用户提问序列（用于底部输入框轮播）
    private let userPrompts = [
        "Help me refactor the authentication module",
        "Fix the memory leak in the WebSocket handler",
        "Add CRUD endpoints for the products API",
        "The dashboard is loading too slowly, optimize it",
        "Commit these changes with a descriptive message",
        "Deploy the latest changes to production",
        "Write tests for the payment service",
        "Design a schema for the notification system",
        "Add i18n support for Japanese and Korean",
        "Run a security audit on the codebase",
    ]
    
    private var currentIndex = 0
    private var currentPromptIndex = 0
    
    func generateNextOutput() -> [TerminalLine] {
        let output = conversations[currentIndex % conversations.count]
        currentIndex += 1
        return output
    }
    
    func nextUserPrompt() -> String {
        let prompt = userPrompts[currentPromptIndex % userPrompts.count]
        currentPromptIndex += 1
        return prompt
    }
}
